// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelKind } from "./ChannelKind";

export type Channel = { id: string, realmId: string, name: string, kind: ChannelKind, };
