// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identify } from "./Identify";
import type { JoinVoice } from "./JoinVoice";
import type { SendMessage } from "./SendMessage";
import type { UpdateProfile } from "./UpdateProfile";
import type { UpdateUserStatus } from "./UpdateUserStatus";
import type { UpdateVoiceState } from "./UpdateVoiceState";

/**
 * Eventos enviados pelo cliente.
 */
export type ClientEvent = { "type": "identify", "data": Identify } | { "type": "sendMessage", "data": SendMessage } | { "type": "joinVoice", "data": JoinVoice } | { "type": "leaveVoice" } | { "type": "updateVoiceState", "data": UpdateVoiceState } | { "type": "updateUserStatus", "data": UpdateUserStatus } | { "type": "updateProfile", "data": UpdateProfile };
