// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identify } from "./Identify";
import type { SendMessage } from "./SendMessage";

/**
 * Eventos enviados pelo cliente.
 */
export type ClientEvent = { "type": "identify", "data": Identify } | { "type": "sendMessage", "data": SendMessage };
