// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type Message = { id: string, channelId: string, author: User, content: string, 
/**
 * Unix epoch em milissegundos.
 */
sentAt: number, };
