// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Realm } from "./Realm";
import type { User } from "./User";

export type Ready = { user: User, realms: Array<Realm>, online: Array<User>, };
