// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from "./Channel";
import type { RealmKind } from "./RealmKind";

/**
 * Um "Realm" é o equivalente a um servidor do Discord / time do Teams.
 */
export type Realm = { id: string, name: string, kind: RealmKind, channels: Array<Channel>, };
