// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelCreated } from "./ChannelCreated";
import type { ChannelDeleted } from "./ChannelDeleted";
import type { ChannelEdited } from "./ChannelEdited";
import type { ErrorPayload } from "./ErrorPayload";
import type { Message } from "./Message";
import type { Ready } from "./Ready";
import type { User } from "./User";
import type { VoicePresenceUpdated } from "./VoicePresenceUpdated";

/**
 * Eventos enviados pelo servidor.
 */
export type ServerEvent = { "type": "ready", "data": Ready } | { "type": "messageCreated", "data": Message } | { "type": "userJoined", "data": User } | { "type": "userLeft", "data": User } | { "type": "userUpdated", "data": User } | { "type": "voicePresenceUpdated", "data": VoicePresenceUpdated } | { "type": "channelCreated", "data": ChannelCreated } | { "type": "channelEdited", "data": ChannelEdited } | { "type": "channelDeleted", "data": ChannelDeleted } | { "type": "error", "data": ErrorPayload };
