// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorPayload } from "./ErrorPayload";
import type { Message } from "./Message";
import type { Ready } from "./Ready";
import type { User } from "./User";
import type { VoicePresenceUpdated } from "./VoicePresenceUpdated";

/**
 * Eventos enviados pelo servidor.
 */
export type ServerEvent = { "type": "ready", "data": Ready } | { "type": "messageCreated", "data": Message } | { "type": "userJoined", "data": User } | { "type": "userLeft", "data": User } | { "type": "userUpdated", "data": User } | { "type": "voicePresenceUpdated", "data": VoicePresenceUpdated } | { "type": "error", "data": ErrorPayload };
