// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProfile = { username: string | null, avatarUrl: string | null, bannerColor: string | null, bio: string | null, };
