// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserStatus } from "./UserStatus";

export type User = { id: string, username: string, status: UserStatus, avatar_url: string | null, banner_color: string | null, bio: string | null, };
