// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceParticipant } from "./VoiceParticipant";

export type VoicePresenceUpdated = { channelId: string, participants: Array<VoiceParticipant>, };
